config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :patients, only: %w[index show new create edit update] do
    member do
      post 'discharge_patient', to: 'patients#discharge_patient', as: 'discharge'
    end
  end

  resources :rooms, only: %w[index show new create update] do
    member do
      get 'add_patients', to: 'rooms#add_patients', as: 'add_patients_to'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
  AVAILABLE_GENDERS = %w[Male Female Non-Binary Undeclared]

  belongs_to :room, optional: true
  has_many :appointments
  has_many :doctors, through: :appointments

  validates :gender, inclusion: { in: AVAILABLE_GENDERS }
  validates :name, :age, :gender, presence: true

  validate :patient_able_to_enter_room?, :changed_to_valid_room?

  def allocate_to_room(new_room)
    self.room = new_room
    save
  end

  def discharge
    update(under_care: false, room: nil)
  end

  private

  def patient_able_to_enter_room?
    if room_changed? && room.present? && !room.space_left_in_room?
      errors.add(:base, "This room is full")
    end
  end

  def changed_to_valid_room?
    if under_care && room_changed? && !room.present?
      errors.add(:base, "Please select a valid room")
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :patients

  validates :capacity, presence: true
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }

  def current_occupancy
    patients.count
  end

  def space_left_in_room?
    current_occupancy < capacity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %w[show edit update discharge_patient]

  def index
    @patients = Patient.includes(:room).all.order(:id)
  end

  def show
    @room = @patient.room
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to patients_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    find_room_ids
  end

  def update
    room_id = params[:patient][:room_id]
    room = Room.find(room_id) unless room_id.blank?

    new_params = patient_params.merge(room: room)

    if @patient.update(new_params)
      redirect_to patients_path
    else
      @errors = @patient.errors.full_messages.join(" / ")

      edit
      render :edit, status: :unprocessable_entity
    end
  end

  def discharge_patient
    if @patient.discharge
      redirect_to @patient
    else
      @errors = @patient.errors.full_messages.join(" / ")

      edit
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :age, :cpf, :gender, :room_id, :under_care)
  end

  def set_patient
    @patient = Patient.includes(:room).find(params[:id])
  end

  def find_room_ids
    @room_ids = Room.pluck(:id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %w[show update add_patients]

  def show
    # Include current_occupancy as a scope?
  end

  def index
    @rooms = Room.includes(:patients).all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to rooms_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def add_patients
    respond_to do |format|
      format.html {
        @patients_without_room = Patient.where(room_id: nil).order(:name)
        @spots_in_room = @room.capacity - @room.current_occupancy
      }
      format.json {
        errors_arr = []

        error_hash = params.select { |key| key.match(/error_\d+/) }
        error_hash.each_value do |error|
          errors_arr << error
        end

        @errors = errors_arr.join(" / ")
      }
    end
  end

  def update
    patient_ids = params[:room][:patient_ids].compact_blank

    @errors = []
    allocate_patients_to_rooms(patient_ids) unless patient_ids.empty?

    redirect_to @room if @errors.blank?
  end

  private

  def room_params
    params.require(:room).permit(:capacity)
  end

  def set_room
    @room = Room.includes(:patients).find(params[:id])
  end

  def allocate_patients_to_rooms(patient_ids)
    patient_ids.each do |patient_id|
      patient = Patient.find(patient_id)

      unless patient.allocate_to_room(@room)
        @errors = patient.errors.full_messages.join(" / ")

        add_patients
        render :add_patients, status: :unprocessable_entity
        break
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHospital</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/patients/edit.html.erb
<div class="container my-3">
  <%= simple_form_for @patient do |f| %>
  <%= f.input :name %>
  <% unless @patient.under_care%>
    <%= f.input :under_care, label: "Admit into care?" %>
  <% end %>
  <%= f.input :age %>
  <%= f.input :cpf, label_html: { class: 'text-uppercase' } %>
  <%= f.input :gender, collection: Patient::AVAILABLE_GENDERS %>
  <%= f.association :room, collection: @room_ids %>
  <% if @errors %>
    <%= render partial: 'shared/custom_error_messages', locals: { error_messages: @errors } %>
  <% end %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

  <div class="row my-3">
    <div class="d-flex">
      <%= link_to "Back to all Patients", patients_path, class: "btn btn-secondary" %>
    </div>
  </div>

  <% if @patient.under_care %>
    <div class="row my-3">
      <div class="d-flex">
        <%= link_to "Discharge patient", discharge_patient_path, class: "btn btn-danger fw-bold",
            data: { turbo_confirm: "Confirm discharging patient?", turbo_method: :post } %>
      </div>
    </div>
  <% end %>
</div>

app/views/patients/index.html.erb
<div class="container">
  <h1 class="my-3">All Patients:</h1>
  <div class="row d-flex">
    <% @patients.each do |patient| %>
      <div class="card col-3 mx-5 my-3">
        <%= link_to patient.name, patient %>
        <% if patient.room%>
          <p>Staying at: <%= link_to "Room #{patient.room.id}", room_path(patient.room) %></p>
        <% elsif patient.under_care %>
          <p>Patient currently does not have a room</p>
        <% else %>
          <p>Patient currently not under care</p>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="row my-3 ms-4">
    <div class="d-flex">
      <%= link_to "Add a new patient", new_patient_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row my-3 ms-4">
    <div class="d-flex">
      <%= link_to "See all rooms", rooms_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<div class="container my-3">
  <%= simple_form_for @patient do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :cpf, label_html: { class: 'text-uppercase' } %>
  <%= f.input :gender, collection: Patient::AVAILABLE_GENDERS %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>


  <div class="row my-3">
    <div class="d-flex">
      <%= link_to "Back to all Patients", patients_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/patients/show.html.erb
<div class="container">
  <h1 class="my-3">Patient <%= @patient.name %></h1>
  <ul>
    <li>Age: <%= @patient.age %></li>
    <li>Gender: <%= @patient.gender %></li>
    <% if @room %>
      <li> Staying at: <%= link_to "Room #{@room.id}", room_path(@room) %></li>
    <% elsif @patient.under_care %>
      <li>Patient currently does not have a room</li>
    <% else %>
      <li>Patient currently not under care</li>
    <% end %>
  </ul>

  <div class="row my-3">
    <div class="d-flex">
      <%= link_to "Edit patient", edit_patient_path(@patient), class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row my-3">
    <div class="d-flex">
      <%= link_to "Back to all patients", patients_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/rooms/add_patients.html.erb
<div class="container my-3"
     data-controller="add-patients-to-room"
     data-add-patients-to-room-spots-in-room-value="<%= @spots_in_room %>">
  <h1 class="mb-3">Add patients to room <%= @room.id %></h1>
  <%= simple_form_for @room do |f| %>
    <%= f.association :patients, collection: @patients_without_room, as: :check_boxes,
          input_html: {
            data: {
              add_patients_to_room_target: "patientCheckbox",
              action: "change->add-patients-to-room#checkSpotsInRoom"
            }
          }
      %>


    <% if @errors %>
      <%= render partial: 'shared/custom_error_messages', locals: { error_messages: @errors } %>
    <% end %>

    <%= f.button :submit, class: "btn btn-primary mb-3" %>
    <div id="error-messages"
         data-add-patients-to-room-target="errorMessagesDiv"
    ></div>
  <% end %>

  <div class="row my-3">
    <div class="d-flex">
      <%= link_to "Back to room page", @room, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container">
  <h1 class="my-3">All Rooms:</h1>
  <div class="row my-3 d-flex">
    <% @rooms.each do |room| %>
      <div class="card col-2 mx-3">
        <div class="align-self-center">
          <%= link_to "Room #{room.id}", room %> <%="(#{room.current_occupancy} / #{room.capacity})" %>
        </div>
        <p class="mt-3 mb-0">Current patients:</p>
        <ul>
        <% room.patients.each do |patient| %>
          <li><%= link_to patient.name, patient %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <div class="row my-3">
    <div class="d-flex">
      <%= link_to "Create new Room", new_room_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row my-3">
    <div class="d-flex">
      <%= link_to "See all patients", patients_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container my-3">
  <%= simple_form_for @room do |f| %>
  <%= f.input :capacity %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="container">
  <h1 class="my-3">Room <%= @room.id %></h1>
  <h6>Current Patients:</h6>
  <div class="row d-flex col-3 ps-2">
    <% @room.patients.each do |patient| %>
      <div class="card col-12 my-2">
        <%= link_to patient.name, patient %>
      </div>
    <% end %>
  </div>

  <% if @room.space_left_in_room? %>
    <div class="row my-3">
      <div class="d-flex">
        <%= link_to "Add patients to room", add_patients_to_room_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <div class="row my-3">
    <div class="d-flex">
      <%= link_to "Back to all rooms", rooms_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/shared/_custom_error_messages.html.erb
<div id="error_messages" class="mb-3 fw-bold small text-danger"><%= error_messages %></div>